name: ClusterFuzzLite coverage
on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:
permissions: read-all
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Build fuzzers (coverage)
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: coverage
      - name: Run fuzzers (coverage)
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: 'coverage'
          sanitizer: 'coverage'
